---
- name: install mysql
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.mysql

  tasks:
    - name: docker packages installation
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: démarrer mysql
      systemd:
        name: mariadb.service
        state: started
        enabled: yes

    - name: Install bottle python package
      ansible.builtin.pip:
        name: pymysql

    - name: install db
      mysql_db:
        name: bobby
        state: present
