---
- name: install mysql
  hosts: all
  collections:
    - community.mysql

  tasks:
    - name: docker packages installation
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - mariadb-server

    - name: démarrer mysql
      systemd:
        name: mariadb.service
        state: started
        enabled: yes

    - name: set python3.7 interpreter
      set_fact: ansible_python_interpreter="/usr/bin/python3"

    - name: Install pymysql python package
      ansible.builtin.pip:
        name: pymysql

    - name: install db
      mysql_db:
        name: bobby
        state: present
